# Generated by Django 5.1.3 on 2024-11-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultistats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
