# Generated by Django 5.1.3 on 2024-12-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultistats', '0003_remove_gamestats_catches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='loss_count',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win_count',
        ),
    ]
