# Generated by Django 5.1.3 on 2024-12-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultistats', '0004_remove_team_loss_count_remove_team_win_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
