# Generated by Django 5.1.3 on 2024-12-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultistats', '0006_team_losses_team_rank_team_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='college_conference',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='college_region',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
