# Generated by Django 5.1.3 on 2024-12-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultistats', '0007_team_college_conference_team_college_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
