# Generated by Django 5.1.1 on 2024-10-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_rename_message_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='StatusMessage',
            new_name='status',
        ),
    ]
