# Generated by Django 5.1.1 on 2024-10-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0007_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
